---
title: ШТАМП СТОР
timezone: Europe/Kiev
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  places:
    title: Изготовление печатей в
    output: true
    permalink: "/izgotovlenie-pechatej/:title/"
  pechati:
    title: Печати
    output: true
    permalink: "/izgotovlenie-pechatej/:title/"
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: landing
    category: project
twitter: ''
github: ''
baseurl: "/"
url: https://stampstore.com.ua
markdown: kramdown
locale: RU_ru
lang: ru
plugins:
- jekyll-seo-tag
excerpt_seperator: "<!--more-->"
destination: "./build"
permalink: "/:title/"
exclude:
- components
- Gemfile
- Gemfile.lock
- ".gitignore"
- node_modules
- js/source.js
- webpack.config.js
- package.json
- ".jshintrc"
- ".sass-cache"
- browser-sync.js
- npm-debug.log
- README.MD
include:
- _pages
sass:
  style: compressed
google_analytics: UA-42310833-1
