
# Info
title: ШТАМП СТОР
twitter: "http://twitter.com/bryanschuetz"
github: "http://github.com/bryanschuetz"
baseurl: "http://localhost:8080"
url: "http://localhost:8080"

# Collections
collections:
  posts:
    title: Posts
    output: true
    permalink: "/news/:title"
  pechati:
    title: Печати
    output: true
    permalink: "/izgotovlenie-pechatej/:title/"
  places:
    title: Изготовление печатей в
    output: true
    permalink: "/izgotovlenie-pechatej/:title/"

# Settings
markdown: kramdown
timezone: Europe/Kiev
locale: RU_ru
lang: ru
plugins:
  - jekyll-seo-tag
excerpt_seperator: "<!--more-->"
destination: "./build"
permalink: "/:titsle"
exclude:
  - components
  - Gemfile
  - Gemfile.lock
  - ".gitignore"
  - node_modules
  - js/source.js
  - webpack.config.js
  - package.json
  - .jshintrc
  - .sass-cache
  - browser-sync.js
  - npm-debug.log
  - README.MD
include: ["_pages"]
sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "landing"
      category: "project"
