description: |
  «ШТАМП СТОР» - СРОЧНОЕ ИЗГОТОВЛЕНИЕ ПЕЧАТЕЙ, ШТАМПОВ И ФАКСИМИЛЕ. Пункт выдачи нашей компании находится на Оболони, в 1 минуте ходьбы от ст.метро Минская. Благодаря современному оборудованию американского производства и высокачественным австрийским расходным материалам мы производим лучший в Украине продукт, которому нет равных. Наши бизнес процессы позволяют нам производить лучшие печати и штампы при наиболее низкой стоимости производства. Мы изготавиливаем печати и штампы для клиентов по всей Украине. Срок доставки и изготовлния с момента заказа для областей занимает 1-2 дня, для Киева - в день заказа. 
phones:
  - +38-044-587-56-73
  - +38-044-587-56-72
email: stamp-market@ukr.net
benefits:
  - Лазерная гравировка
  - Износостойкая резина
  - Бесплатная доставка по Киеву
  - Доставка по всей Украине за 1 день
  - Гарантия качества