title: "Static, Meet Dynamic."
description: |
  «ШТАМП СТОР» - СРОЧНОЕ ИЗГОТОВЛЕНИЕ ПЕЧАТЕЙ, ШТАМПОВ И ФАКСИМИЛЕ. Пункт выдачи нашей компании находится на Оболони, в 1 минуте ходьбы от ст.метро Минская. Благодаря современному оборудованию американского производства и высокачественным австрийским расходным материалам мы производим лучший в Украине продукт, которому нет равных. Наши бизнес процессы позволяют нам производить лучшие печати и штампы при наиболее низкой стоимости производства. Мы изготавиливаем печати и штампы для клиентов по всей Украине. Срок доставки и изготовлния с момента заказа для областей занимает 1-2 дня, для Киева - в день заказа. 
combination: |
  Take the best parts of a static site workflow and combine them with the new hotness of a client side framework. What you end up with is a great new way to publish content on the modern web. Isomorphic blah blah blah: Use Jekyll to publish the site's pages, and the JSON data behind them—use Vue to build the same pages with the same data. Serve the first static page to the user—if JS is supported, just send the JSON down the wire and build the rest of the pages/content with Vue. If there's no JS support, continue to send pre-rendered static pages down the wire.
staticBenefits:
  - speed (cdn/pre-rendered)
  - cacheability
  - reliability 
  - developer workflow
dynamicBenefits:
  - speed (ui/ux)
  - isomorphic rendering
  - complex state management
  - dynamic components
phones:
  - +38-044-587-56-73
  - +38-044-587-56-72